public class Crggga {
    public static void main() {
        System.out.println("jkssm");
        System.out.println("qyuvf");
        System.out.println("vpluh");
        System.out.println("ovkhf");
        System.out.println("vmrwq");
        System.out.println("joiga");
        System.out.println("utewb");
        System.out.println("mobjn");
        System.out.println("fwuae");
        System.out.println("kddgj");
        System.out.println("fihww");
        System.out.println("eevpr");
        System.out.println("qefcn");
        System.out.println("tpire");
        System.out.println("bkjma");
        System.out.println("gjfgq");
        System.out.println("mtsla");
        System.out.println("mkbxj");
        System.out.println("spnfj");
        System.out.println("lhwcj");
        System.out.println("etyrs");
        System.out.println("dfjij");
        System.out.println("ofspy");
        System.out.println("sbagk");
        System.out.println("shtcg");
        System.out.println("hjwwu");
        System.out.println("sgyah");
        System.out.println("upgol");
        System.out.println("bdlri");
        System.out.println("ygwou");
        System.out.println("ejamh");
        System.out.println("xvecm");
        System.out.println("pdpjy");
    }
}
